[tool.poetry]
name = "football-scheduler"
version = "0.1.0"
description = ""
authors = ["karlsteinborn <steinborn.k@smallsparkspace.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
